spring:
  application:
    name: todos
  datasource:
    driver-class-name: org.sqlite.JDBC
    username: viktor
    password: Str0ngP
    url: jdbc:sqlite:test-db.db
    hikari:
      auto-commit: false

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    generate-ddl: false

  port: 8080

grpc:
  server:
    port: 9090

#management.endpoints.web.exposure.include: metrics
management.endpoint.metrics.enabled: true

